config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  draw :sidekiq

  root 'items#index'

  devise_for :admins
  devise_for :users

  resources :items, only: %i[index]
  resources :cart_items, only: %i[index create destroy]

  namespace :admins do
    resources :processors, only: %i[index create]
    resource :processors, only: %i[destroy]
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bobswatches_item.rb
# frozen_string_literal: true

class BobswatchesItem < Item
  MIN_FEATURE_LENGTH = 2

  store_accessor :features, :box_and_papers, :year, :gender, :condition, :regular_price

  validates :box_and_papers, :year, :gender, :condition, :regular_price,
            length: { minimum: MIN_FEATURE_LENGTH }, allow_blank: true
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/crownandcaliber_item.rb
# frozen_string_literal: true

class CrownandcaliberItem < Item
  MIN_FEATURE_LENGTH = 2

  store_accessor :features, :papers, :box, :year, :gender, :crystal, :condition,
                 :caseback, :power_reserve, :lug_width, :bezel_material, :manual,
                 :max_wrist_size, :case_thickness

  validates :papers, :box, :year, :gender, :crystal, :condition, :caseback, :power_reserve,
            :lug_width, :bezel_material, :manual, :max_wrist_size, :case_thickness,
            length: { minimum: MIN_FEATURE_LENGTH }, allow_blank: true
end

app/models/hodinkee_item.rb
# frozen_string_literal: true

class HodinkeeItem < Item
  MIN_FEATURE_LENGTH = 2

  store_accessor :features, :crystal, :water_resistance, :functions,
                 :caseback, :power_reserve, :manufactured, :lug_width, :lume

  validates :crystal, :water_resistance, :functions, :caseback,
            :power_reserve, :manufactured, :lug_width, :lume,
            length: { minimum: MIN_FEATURE_LENGTH }, allow_blank: true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  TYPES = %w[HodinkeeItem CrownandcaliberItem BobswatchesItem].freeze

  has_many :cart_items, dependent: :destroy

  enum currency: {
    usd: 'usd',
    eur: 'eur',
    uah: 'uah'
  }, _prefix: true
  validates :type, :price, :currency, :external_id, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :external_id, uniqueness: true

  scope :by_brands, lambda { |brands|
    return all if brands.blank?

    where(brands.map { |brand| sanitize_sql(['brand ILIKE ?', "%#{brand}%"]) }.join(' OR '))
  }
  scope :by_model, ->(model) { model.blank? ? all : where('model ILIKE ?', "%#{model}%") }
  scope :by_dial_color, ->(dial_color) { dial_color.blank? ? all : where('dial_color ILIKE ?', "%#{dial_color}%") }
  scope :by_case_material, lambda { |case_material|
    case_material.blank? ? all : where('case_material ILIKE ?', "%#{case_material}%")
  }
  scope :by_case_dimensions, lambda { |case_dimensions|
    case_dimensions.blank? ? all : where('case_dimensions ILIKE ?', "%#{case_dimensions}%")
  }
  scope :by_bracelet_material, lambda { |bracelet_material|
    return all if bracelet_material.blank?

    where('bracelet_material ILIKE ?', "%#{bracelet_material}%")
  }
  scope :by_movement_type, lambda { |movement_type|
    movement_type.blank? ? all : where('movement_type ILIKE ?', "%#{movement_type}%")
  }

  scope :ordered_by_brand_asc, -> { order(brand: :asc) }
  scope :ordered_by_brand_desc, -> { order(brand: :desc) }
  scope :ordered_by_price_asc, -> { order(price: :asc) }
  scope :ordered_by_price_desc, -> { order(price: :desc) }

  scope :by_price, lambda { |min_price: 0, max_price: nil|
    query = all
    query = query.where('price >= ?', min_price) if min_price.to_f.positive?
    query = query.where('price <= ?', max_price) if max_price.present?
    query
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
end

app/controllers/admin/processors_controller.rb
# frozen_string_literal: true

module Admin
  class ProcessorsController < ApplicationController
    def index
      @redis = Redis.current
    end

    def create
      Processors::Controller.new.run

      redirect_to admin_processors_path, notice: t('processors.start')
    end

    def destroy
      Processors::Controller.new.stop

      redirect_to admin_processors_path, notice: t('processors.stop')
    end
  end
end

app/controllers/admins/processors_controller.rb
# frozen_string_literal: true

module Admins
  class ProcessorsController < ApplicationController
    before_action :authenticate_admin!

    def index
      @redis = Redis.current
    end

    def create
      Processors::Controller.new.run

      redirect_to admins_processors_path, notice: t('processors.start')
    end

    def destroy
      Processors::Controller.new.stop

      redirect_to admins_processors_path, notice: t('processors.stop')
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :count_items

  private

  def count_items
    @item_numbers = Item.count
  end
end

app/controllers/cart_items_controller.rb
# frozen_string_literal: true

class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @data = CartItems::Index.new(current_user)
  end

  def create
    if CartItem.create(cart_item_params).errors.any?
      redirect_to items_path, alert: t('error')
    else
      redirect_to items_path, notice: t('cart.add')
    end
  end

  def destroy
    CartItem.find_by(item_id: params[:id]).destroy!

    redirect_to cart_items_path, notice: t('cart.delete')
  end

  private

  def cart_item_params
    params.permit(:item_id, :user_id)
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @data = Items::Index.new(params, current_user)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/processors/index.html.erb
<div class="container">
  <div class="mt-5 center">
    <div style="display: inline-block"
         class="center-align tooltipped"
         data-position="bottom"
         data-tooltip="<%= t('processors.start_date', datetime: @redis.get('parsing:run:datetime')) %>">
      <%= link_to admin_processors_path,
                  class: "waves-effect btn-large teal lighten-1 #{'disabled' if @redis.get('parsing:run').present?}",
                  method: :post do %>
                    Run
                    <i class="material-icons right">play_arrow</i>
                  <% end %>
    </div>

    <div style="display: inline-block"
         class="center-align tooltipped"
         data-position="bottom"
         data-tooltip="<%= t('processors.stop_date', datetime: @redis.get('parsing:stop:datetime')) %>">
      <%= link_to admin_processors_path,
                  class: "waves-effect btn-large red lighten-1 #{'disabled' if @redis.get('parsing:run').blank?}",
                  method: :delete do %>
                    Stop
                    <i class="material-icons right">stop</i>
                  <% end %>
    </div>
  </div>
  <div class="mt-5">
    <% if @redis.get('parsing:run').present? %>
      <div class="progress">
        <div class="indeterminate"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/processors/index.html.slim
.container
  .mt-5.center
    .center-align.tooltipped data-position="bottom" data-tooltip="#{t('processors.start_date', datetime: @redis.get('parsing:run:datetime'))}" style=("display: inline-block")
      = link_to admins_processors_path,
              class: "waves-effect btn-large teal lighten-1 #{'disabled' if @redis.get('parsing:run').present?}",
              method: :post do
        | Run
        i.material-icons.right play_arrow
    .center-align.tooltipped data-position="bottom" data-tooltip="#{t('processors.stop_date', datetime: @redis.get('parsing:stop:datetime'))}" style=("display: inline-block")
      = link_to admins_processors_path,
              class: "waves-effect btn-large red lighten-1 #{'disabled' if @redis.get('parsing:run').blank?}",
              method: :delete do
        | Stop
        i.material-icons.right stop
  .mt-5
    - if @redis.get('parsing:run').present?
      .progress
        .indeterminate

app/views/cart_items/index.html.slim
.mt-5.flex-center
  .wd-5
    h2.center
      = t('cart.title')
    - if @data.items_in_cart.present?
      - @data.items_in_cart.each do |item|
        ul.collection
          li.collection-item.avatar
            = item.image_uri.present? ? image_tag(item.image_uri, height: '50', class: 'circle materialboxed') : image_pack_tag('placoholder.png', height: '50')
            span.title
              = item.brand
            p
              = item.model
              .red-text
                = "#{item.price} #{item.currency.upcase}"
            = link_to cart_item_path(item.id), method: :delete, class: 'secondary-content' do
              i.material-icons.medium delete_forever
      h5.mt-3.right-align
        = "#{t('cart.total')} #{@data.total_in_cart}"

    - else
      .col.s6
        p.has-text-centered.is-size-6
          = t('items.no_items')

app/views/items/_search_form.erb
<%= search_form_for search, type: 'text' do |f| %>
  <div class='fixed-container'>
    <form>
      <div class="row">
        <div class="input-field mt-3">
          <div class="form-group">
            <%= f.select(:brand_cont,
                         options_for_select(data.brands_for_select, selected: f.object.brand_cont),
                         prompt: t('items.search_hint.brand')) %>
            <%= f.label :brand %>
          </div>
        </div>
        <div class="input-field mt-3">
          <%= f.search_field :model_cont,
                             placeholder: t('items.search_hint.model'),
                             type: 'text',
                             class: 'validate' %>
          <%= f.label :model %>
        </div>
        <div class="form-group">
          <%= f.label :price %>
          <div class="row">
            <div class="col s6">
              <%= f.text_field :price_gteq,
                               class: 'form-control',
                               id: 'min-price-output',
                               data: { default: data.default_min_price },
                               value: data.current_min_price %>
            </div>
            <div class="col s6">
              <%= f.text_field :price_lteq,
                               class: 'form-control',
                               id: 'max-price-output',
                               data: { default: data.default_max_price },
                               value: data.current_max_price %>
            </div>
          </div>
        </div>
        <div class="price-slider" style="margin-bottom: 80px"></div>
        <div class="mt-5">
          <div class="input-field mt-3">
            <%= f.search_field :dial_color_cont,
                               placeholder: t('items.search_hint.dial_color'),
                               type: 'text',
                               class: 'validate' %>
            <%= f.label :dial_color %>
          </div>
          <div class="input-field mt-3">
            <%= f.search_field :case_material_cont,
                               placeholder: t('items.search_hint.case_material'),
                               type: 'text',
                               class: 'validate' %>
            <%= f.label :case_material %>
          </div>
          <div class="input-field mt-3">
            <%= f.search_field :case_dimensions_cont,
                               placeholder: t('items.search_hint.case_dimensions'),
                               type: 'text',
                               class: 'validate' %>
            <%= f.label :case_dimensions %>
          </div>
          <div class="input-field mt-3">
            <%= f.search_field :bracelet_material_cont,
                               placeholder: t('items.search_hint.bracelet_material'),
                               type: 'text',
                               class: 'validate' %>
            <%= f.label :bracelet_material %>
          </div>
          <div class="input-field mt-3">
            <%= f.search_field :movement_type_cont,
                               placeholder: t('items.search_hint.movement_type'),
                               type: 'text',
                               class: 'validate' %>
            <%= f.label :movement_type %>
          </div>
        </div>
      </div>
    </form>

    <div class="center">
      <div class="input-field" style="display: inline-block">
        <button class="btn waves-effect" type="submit" name="action">Search</button>
        <%= link_to 'Clear', request.path, class: 'btn waves-effect' %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/_search_form.html.slim
.fixed-container
  = form_with url: items_path, method: :get, data: { remote: false } do |f|
    .form-group
      .row
        .col.s6
          p
          label
            = f.radio_button :sort, 'brandASC', checked: params[:sort].eql?('brandASC')
            span
              | Brand ASC
              i.right.material-icons arrow_drop_down
          p
          label
            = f.radio_button :sort, 'brandDESC', checked: params[:sort].eql?('brandDESC')
            span
              | Brand DESC
              i.right.material-icons arrow_drop_up

        .col.s6
          p
            label
              = f.radio_button :sort, 'priceASC', checked: params[:sort].eql?('priceASC')
              span
                | Price ASC
                i.right.material-icons arrow_drop_down
          p
            label
              = f.radio_button :sort, 'priceDESC', checked: params[:sort].eql?('priceDESC')
              span
                | Price DESC
                i.right.material-icons arrow_drop_up

        .col.s12
          .input-field.mt-3
            = f.select :brands,
                    options_for_select(data.brands_for_select, params[:brands]),
                    { include_hidden: false, prompt: false },
                    multiple: true,
                    data: { placeholder: t('items.search_hint.brand') }
            = f.label :brands
          .input-field.mt-3
            = f.search_field :model,
                    placeholder: t('items.search_hint.model'),
                    type: 'text',
                    class: 'validate',
                    value: params[:model]
            = f.label :model
          .form-group
            = f.label :price
            .row
              .col.s6
                = f.text_field :price_gteq,
                        class: 'form-control',
                        id: 'min-price-output',
                        data: { default: data.default_min_price },
                        value: params[:price_gteq]
              .col.s6
                = f.text_field :price_lteq,
                        class: 'form-control',
                        id: 'max-price-output',
                        data: { default: data.default_max_price },
                        value: params[:price_lteq]
          .price-slider[style="margin-bottom: 50px"]
          .row
            .col.s6
              .input-field.mt-3
                = f.search_field :dial_color,
                        placeholder: t('items.search_hint.dial_color'),
                        type: 'text',
                        class: 'validate',
                        value: params[:dial_color],
                        list: 'colors'
                datalist#colors
                  - t('items.predefined_values.colors', default: {}).sort.each do |value|
                    |  <option value="
                    = value
                    | ">
                = f.label :dial_color
            .col.s6
              .input-field.mt-3
                = f.search_field :case_dimensions,
                        placeholder: t('items.search_hint.case_dimensions'),
                        type: 'text',
                        class: 'validate',
                        value: params[:case_dimensions]
                = f.label :case_dimensions
          .input-field.mt-3
            = f.search_field :case_material,
                    placeholder: t('items.search_hint.case_material'),
                    type: 'text',
                    class: 'validate',
                    value: params[:case_material],
                    list: 'case-materials'
            datalist#case-materials
              - t('items.predefined_values.case_materials', default: {}).sort.each do |value|
                |  <option value="
                = value
                | ">
            = f.label :case_material
          .input-field.mt-3
            = f.search_field :bracelet_material,
                    placeholder: t('items.search_hint.bracelet_material'),
                    type: 'text',
                    class: 'validate',
                    value: params[:bracelet_material],
                    list: 'bracelet-materials'
            datalist#bracelet-materials
              - t('items.predefined_values.bracelet_materials', default: {}).sort.each do |value|
                |  <option value="#{value}">
            = f.label :bracelet_material
          .input-field.mt-3
            = f.search_field :movement_type,
                    placeholder: t('items.search_hint.movement_type'),
                    type: 'text',
                    class: 'validate',
                    value: params[:movement_type],
                    list: 'movements'
            datalist#movements
              - t('items.predefined_values.movements', default: {}).sort.each do |value|
                |  <option value="#{value}">
            = f.label :movement_type
          .center
            div[style="display: inline-block"]
              button.btn.waves-effect[type="submit"]
                | Search
              = link_to 'Clear', request.path, class: 'btn waves-effect'

app/views/items/index.html.slim
.row
  .col.s3
    = render 'items/search_form', data: @data
  - if @data.items.any?
    .col.s9
      table.highlight.centered.striped.responsive-table
        thead
          tr
            th
              = 'Image'
            th
              = t('items.table.brand')
            th
              = t('items.table.model')
            th
              = t('items.table.price')
            th
              = t('items.table.dial')
            th
              = t('items.table.case_material')
            th
              = t('items.table.case_dimensions')
            th
              = t('items.table.bracelet')
            th
              = t('items.table.movement')
            th
              =
        - @data.items.each do |item|
            tr class="#{'grey-text' if @data.in_cart?(item)}"
              td style="#{'opacity: 0.5;' if @data.in_cart?(item)}"
                = item.image_uri.present? ? image_tag(item.image_uri, height: '200', class: 'circle materialboxed') : image_pack_tag('placoholder.png', height: '200')
              td
                = item.brand
              td
                = item.model
              td
                = "#{item.price} #{item.currency.upcase}"
              td
                = item.dial_color
              td
                = item.case_material
              td
                = item.case_dimensions
              td
                = item.bracelet_material
              td
                = item.movement_type
              td
                - if user_signed_in?
                  = link_to cart_items_path(item_id: item.id, user_id: current_user.id), method: :post, class: "btn waves-effect #{'disabled' if @data.in_cart?(item)}" do
                    i.material-icons add_shopping_cart
                - else
                  = link_to cart_items_path, class: "btn waves-effect " do
                    i.material-icons add_shopping_cart
  - else
    .col.s9.mt-5
      p.has-text-centered.is-size-6
        = t('items.no_items')

app/views/layouts/_header.html.slim
.navbar-fixed
  nav.teal
    .container.nav-wrapper
      = image_pack_tag 'logo.png'
      ul#nav-mobile.right.hide-on-med-and-down
        li
          - if admin_signed_in?
            = link_to edit_admin_registration_path do
              i.material-icons.left person
              = t('session.admin_profile')
        li
          - if user_signed_in?
            = link_to edit_user_registration_path do
              i.material-icons.left person
              = t('session.user_profile')
        li
          = link_to admins_processors_path do
            i.material-icons.left play_arrow
            = t('processors.nav')
        li
          = link_to items_path do
            i.material-icons.left watch
            = t('items.nav')
            span.new.badge.teal.darken-3[data-badge-caption=""]
              = @item_numbers
        li
          = link_to cart_items_path do
            i.material-icons.left shopping_cart

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | WatchGrabber
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_pack_tag 'favicon.ico'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
  body
    |  <div id="toasts" data-toasts="
    = flash.to_h.to_json
    | ">
    = render 'layouts/header'
    = yield